name = "base64"
description = "Base64 encoding/decoding routines"
version = "0.0.0"
website = "https://github.com/AntonMeep/base64"
licenses = "ISC"
tags = ["base64"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]
